### ISSUE TITLE
Need help to open row data

### ISSUE THREAD

**Issue by mownica10** [syncfusion/ej2-javascript-docs#3]
My query is, when i click the **customer id** column it has to open the row data dialog.  Currently what i'm having is "when i double tab on any column field it is opening" But i don't need that. The dialog box has to be open only if i click any of the column field inside customer id alone.  

The current code which i'm usins as app.ts
import { Grid, Edit, Toolbar, DialogEditEventArgs } from '@syncfusion/ej2-grids';
import { data } from './data-source';
import { DataUtil } from '@syncfusion/ej2-data';
import { Dialog } from '@syncfusion/ej2-popups';
import { enableRipple } from '@syncfusion/ej2-base';
import { DropDownList } from '@syncfusion/ej2-dropdowns';
import { CheckBox } from '@syncfusion/ej2-buttons';
import { NumericTextBox } from '@syncfusion/ej2-inputs';

enableRipple(true);

Grid.Inject(Edit, Toolbar);

let countryData: {}[] = DataUtil.distinct(data, 'ShipCountry', false);

let grid: Grid = new Grid({
    dataSource: data,
    editSettings: {  mode: 'Dialog', template: '#dialogtemplate', allowEditing:true},
    
    columns: [
        { field: 'OrderID', headerText: 'Order ID', textAlign: 'Right',  width: 100, isPrimaryKey: true },
        { field: 'CustomerID', headerText: 'Customer ID', allowEditing: false, width: 120,  },
        
    { field: 'ShipCountry', headerText: 'Ship Country',  width: 150 }
    ],
    height: 265,
  
 });

 
grid.appendTo('#Grid');

// function mode(allowEditing: 'CustomerID',arg1: boolean,mode: any,arg3: string,template: 'CustomerID',arg5: string) {
// throw new Error('Function not implemented.');
// }

**Comment by sujithvj** [comment]
Hi @mownica10,

Greetings from Syncfusion.

From the provided information we could understand that your requirement is to enable single click edit only on clicking the required column(in your case - ‘CustomerID’). This can be achieved by following the below steps,

The single click edit can be enabled in the Grid by binding the mouseup event for Grid(from the load event) and in the event handler call the startEdit method based on the clicked target element,

```
// Grid’s load event handler    
function onLoad() {
    // Mouse down event is bound to the Grid element
    grid.element.addEventListener('mousedown', (e: any) => {
        var rowTarget = e.target.classList.contains("e-rowcell");
        if (rowTarget) {
            // Condition executes if the Grid cell is clicked
            let index: number = parseInt(e.target.getAttribute("Index"));
            // The clicked index is selected and moved to edit state 
            grid.selectRow(index);
            grid.startEdit();
        }
    })
}
```

Here you can check condition whether the clicked target cell is the required column before starting the edit as demonstrated below,

```
// Grid’s load event handler
function onLoad() {
    grid.element.addEventListener('mousedown', (e: any) => {
        var rowTarget = e.target.classList.contains("e-rowcell");
        // Get the current clicked row information by passing the row cell to the Grid’s getRowInfo method
        var rowInfo = grid.getRowInfo(e.target);
        if (rowTarget && rowInfo.column.field === "CustomerID") {
                    ...
        }
    })
}
```

We have prepared a sample based on this for your reference. You can find it below,

**Sample:** https://stackblitz.com/edit/qojrub

**API:** https://ej2.syncfusion.com/documentation/api/grid/#load
        https://ej2.syncfusion.com/documentation/api/grid/#selectrow
        https://ej2.syncfusion.com/documentation/api/grid/#startedit
        https://ej2.syncfusion.com/documentation/api/grid/#getrowinfo

Please get back to us if you require any further assistance.

Regards,
Sujith R

**Comment by mownica10** [comment]
thanks for your help. it's working, But i want the clickable only in "customerid". If i double tap of other columns it is opening dialogue box, i don't want that, is there any way to achieve that??

**Comment by VigneshNatarajan27** [comment]
Thanks for the update @mownica10 . We suggest you achieve your requirement by disabling the double click edit action using [AllowEditOnDblClick](https://ej2.syncfusion.com/javascript/documentation/api/grid/editSettings/#alloweditondblclick) property of grid edit settings. Using this property we can prevent the edit on double click action. 

Kindly refer the modified sample from below 

https://stackblitz.com/edit/qojrub-ciayfr 

Refer the API documentation for your reference

https://ej2.syncfusion.com/javascript/documentation/api/grid/editSettings/#alloweditondblclick 

Please get back to us if you have further queries.

**Comment by syncsiva** [comment]
This issue has been resolved and has not had any activity for 1 week. Closing for housekeeping purposes. Please feel free to reopen if you have any further queries.
