### ISSUE TITLE
Highlight search giving error

### ISSUE THREAD

**Issue by AnshilSaxena** [syncfusion/ej2-javascript-docs#4]
Property 'innerText' does not exist on type 'Element'.ts(2339)
![image](https://user-images.githubusercontent.com/77104994/159626238-27f29652-4d13-49b1-8340-5ffa5e67cefa.png)

**Comment by VigneshNatarajan27** [comment]
@AnshilSaxena 

We are able to reproduce the reported issue at our end also. Kindly refer to the below-modified code example to resolve the reported issue.

        args.cell.innerHTML = (args.cell as any).innerText.replaceAll(
          searchStr,
          "<span class='customcss'>" + searchStr + '</span>'
        );


Please find the modified sample below 

https://stackblitz.com/edit/gnaxhm-pokwyq?file=index.ts  

Please get back to us if you have further queries.

**Comment by syncsiva** [comment]
Thanks reporting for issue in docs. It's been corrected, and reflected in live now. 
https://ej2.syncfusion.com/documentation/grid/searching/#highlight-the-search-text
