### ISSUE TITLE
Getting error in column.field

### ISSUE THREAD

**Issue by mownica10** [syncfusion/ej2-javascript-docs#5]
import { Grid, Edit, Toolbar, Page } from '@syncfusion/ej2-grids';
import { orderData } from './data-source';

/**
 * Dialog Editing sample
 */
Grid.Inject(Edit, Toolbar, Page);

    
    let grid: Grid = new Grid(
        {
            dataSource: orderData,
            editSettings: { allowEditing: true, allowAdding: true, allowDeleting: true, mode: 'Dialog' },
            allowPaging: true,
            pageSettings: {pageCount: 5},
            toolbar: ['Add', 'Edit', 'Delete'],
            columns: [
                {
                    field: 'OrderID', isPrimaryKey: true, headerText: 'Order ID', textAlign: 'Right',
                    validationRules: { required: true, number: true }, width: 120
                },
                {
                    field: 'CustomerID', headerText: 'Customer ID',
                    validationRules: { required: true }, width: 140
                },
                {
                    field: 'Freight', headerText: 'Freight', textAlign: 'Right', editType: 'numericedit',
                    width: 120, format: 'C2', validationRules: { required: true }
                },
                {
                    field: 'OrderDate', headerText: 'Order Date', editType: 'datepickeredit',
                    format: 'yMd', width: 170
                },
                {
                    field: 'ShipCountry', headerText: 'Ship Country', editType: 'dropdownedit', width: 150,
                    edit:  { params:  {  popupHeight:  '300px' } }
                }],
                load: onLoad 
        });
    grid.appendTo('#Grid');

    function onLoad() {
            grid.element.addEventListener('mousedown', (e: any) => {
                var rowTarget = e.target.classList.contains("e-rowcell");
                var rowInfo = grid.getRowInfo(e.target);
                if (rowTarget && rowInfo.column.field === "CustomerID") {
                    let index: number = parseInt(e.target.getAttribute("Index"));
                    grid.selectRow(index);
                    grid.startEdit();
                }
            })
    }

**Comment by VigneshNatarajan27** [comment]
@mownica10 

We are able to reproduce the reported issue when preparing a sample as per your code example. Please find the modified code example from below.

`function onLoad() {
  grid.element.addEventListener('mousedown', (e: any) => {
    var rowTarget = e.target.classList.contains('e-rowcell');
    var rowInfo = grid.getRowInfo(e.target);
    if (rowTarget && (rowInfo.column as any).field === 'CustomerID') {
      let index: number = parseInt(e.target.getAttribute('Index'));
      grid.selectRow(index);
      grid.startEdit();
    }
  });
}
`

Kindly refer to the below sample for your reference

https://stackblitz.com/edit/gnaxhm-uwnhqe?file=index.ts

Please get back to us if you have further queries.
