### ISSUE TITLE
Paging template having error "Object is possibly undefined"

### ISSUE THREAD

**Issue by AnshilSaxena** [syncfusion/ej2-javascript-docs#6]
![image](https://user-images.githubusercontent.com/77104994/160336249-0ce38fc4-531c-45a5-8e5c-9f166d659cd6.png)

![image](https://user-images.githubusercontent.com/77104994/160336081-07bf202c-255d-4f8e-b158-6fb5fca2ca43.png)
![image](https://user-images.githubusercontent.com/77104994/160336108-3bc5809a-7ea7-42ce-a297-bd6a177e025b.png)
![image](https://user-images.githubusercontent.com/77104994/160336205-89b09ede-bfae-4bea-a6d5-2d3236fc004f.png)

**Comment by VigneshNatarajan27** [comment]
@AnshilSaxena 

We are able to reproduce the reported issue at our end and we have resolved the issue. It will be reflected online as early as possible. Please find the modified code example below

```
let updateTemplate: Function = () => {
  let numeric: NumericTextBox = new NumericTextBox({
    min: 1,
    max: 3,
    step: 1,
    format: '###.##',
    change: (args) => {
      let value: number = args.value;
      grid.goToPage(value);
    },
  });
  numeric.appendTo('#currentPage');
};
```
 
Kindly refer the below sample for your reference

Sample: https://stackblitz.com/edit/pfb6nb?file=index.ts

Please get back to us if you have further queries.

**Comment by AnshilSaxena** [comment]
Thank you @VigneshNatarajan27
Code is working now..
